/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.school;

import java.awt.Image;

import javax.swing.ImageIcon;
import com.school.AdminUI;
//import DashboardStudent.StudentUI;
import com.school.TeacherUI;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Win8.1
 */
public class LoginUI extends javax.swing.JFrame {

    public String userId,password;
    public int cls,id;
    /**
     * Creates new form LoginUI
     */
    public LoginUI() {
        initComponents();
        //scaleImage();
    }

    
    /*public void scaleImage(){
        ImageIcon icon=new ImageIcon("C:\\Users\\Win8.1\\Downloads\\1.png");
        Image img=icon.getImage();
        Image imgScale=img.getScaledInstance(jLabel6.getWidth(),jLabel6.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        //jLabel6.setIcon(scaledIcon);
    */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 204, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel3.setText("UserID");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 60, -1));

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel4.setText("Password");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 70, -1));

        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 204, 153));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 150, -1));

        jPasswordField1.setBackground(new java.awt.Color(0, 0, 0));
        jPasswordField1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(255, 204, 153));
        jPanel2.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 150, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 204, 153));
        jButton1.setText("LOGIN");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 224, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 500));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/school/S M S (2).gif"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, -80, 470, 650));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userId=jTextField1.getText().toString();
        password=jPasswordField1.getText().toString();
        
        if(password.contains("Admin123") && userId.contains("123")){
            jPasswordField1.setText(null);
            jTextField1.setText(null);
            
            AdminUI scr=new AdminUI();
            scr.setVisible(true);
            this.setVisible(false);
            
        }
        else if(password.contains("Teacher123")){
            
            jPasswordField1.setText(null);
            jTextField1.setText(null);
            try {
                int res=validateT(userId);
                if(res==1){
                    TeacherUI scr=new TeacherUI(userId);
                    scr.setVisible(true);
                    this.setVisible(false);
                }
                else{
                    JOptionPane.showMessageDialog(null, "INVALID ID","ERROR",JOptionPane.ERROR_MESSAGE);
                }
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "INVALID ID","ERROR",JOptionPane.ERROR_MESSAGE);
                //Logger.getLogger(LoginUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if(password.contains("Student123")){
            
            jPasswordField1.setText(null);
            jTextField1.setText(null);
            id=Integer.parseInt(userId);
            cls=id/100;
          
            
            try {
                int res=validateS(userId,cls);
                if(res==1){
                    StudentUI scr=new StudentUI(userId); 
                    scr.setVisible(true);
                    this.setVisible(false);
                }
                else{
                    JOptionPane.showMessageDialog(null, "INVALID ID","ERROR",JOptionPane.ERROR_MESSAGE);
                }
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "INVALID ID","ERROR",JOptionPane.ERROR_MESSAGE);
                //Logger.getLogger(LoginUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            jPasswordField1.setText(null);
            jTextField1.setText(null);
            JOptionPane.showMessageDialog(null, "INVALID ID","ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private int validateT(String userId) throws FileNotFoundException, IOException {
        int val=0;
        String line="";
        BufferedReader reader;
        String filepath="Teachers.csv";
        reader= new BufferedReader(new FileReader(filepath));
         while((line =reader.readLine())!=null){
                String[] fields= line.split(",");
                if(fields[7].equals(userId)){
                    val=1;
                    break;
                }
         }
        
        return val;
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
     private int validateS(String userId,int cls) throws FileNotFoundException, IOException {
        int val=0;
        String line="";
        BufferedReader reader;
        if(cls==1){
            String filepath="1.csv";
            reader= new BufferedReader(new FileReader(filepath));
        }else if(cls==2){
            String filepath="2.csv";
            reader= new BufferedReader(new FileReader(filepath));
        }else if(cls==3){
            String filepath="3.csv";
            reader= new BufferedReader(new FileReader(filepath));
        }else if(cls==4){
            String filepath="4.csv";
            reader= new BufferedReader(new FileReader(filepath));
        }else if(cls==5){
            String filepath="5.csv";
            reader= new BufferedReader(new FileReader(filepath));
        }else{
            return 0;
        }
        
        
         while((line =reader.readLine())!=null){
                String[] fields= line.split(",");
                if(fields[0].equals(userId)){
                    val=1;
                    break;
                }
         }
        
        return val;
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
